spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/eventservice?currentSchema=event
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto:update
server:
  port: 80