spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/classifierservice?currentSchema=classifier
    driver-class-name: org.postgresql.Driver
server:
  port: 8081